Universe              = vanilla
executable            = runSelections.sh
#arguments             = 50000 $(ProcId)
arguments             = 50000 21
GetEnv                = True
output                = output/$(ClusterId).$(ProcId).out
error                 = error/$(ClusterId).$(ProcId).err
log                   = log/$(ClusterId).log
requirements 	      = (OpSysAndVer =?= "CentOS7")
+JobFlavour           = "espresso"

#queue 31
queue 1
